import gradio as gr
import time

def silent_writer_logic(repo_url):
    """
    SilentWriter Demo — 3 cas de démonstration
    Version réelle → appel IBM WatsonX Granite API
    """
    
    time.sleep(1.2)  # Simulation du temps d'analyse IA
    
    url = repo_url.lower()

    # ─── CAS 1 : Breaking change détecté → PR BLOQUÉE ───
    if "breaking" in url or "broken" in url:
        return """
╔══════════════════════════════════════════════╗
║  🤖 SILENTWRITER · IBM GRANITE              ║
╠══════════════════════════════════════════════╣
║  Status: ⛔ PR BLOCKED                      ║
╠══════════════════════════════════════════════╣
║  🔍 Analysis:
║     • Breaking change detected
║     • login() signature modified — apiKey added
║     • 📊 Impact: 47 calls will break
║     • 📚 Documentation: ❌ Outdated
║     • 🤖 agents.md: ❌ Requires update
╠══════════════════════════════════════════════╣
║  ⚡ Action:
║     • PR #42 BLOCKED automatically
║     • SilentWriter opened PR #43 with updated docs
║     • Notified: @tech-lead @architect
╚══════════════════════════════════════════════╝
"""

    # ─── CAS 2 : agents.md auto-généré ───
    elif "agents" in url or "agent" in url:
        return """
╔══════════════════════════════════════════════╗
║  🤖 SILENTWRITER · IBM GRANITE              ║
╠══════════════════════════════════════════════╣
║  Status: 🤖 AGENTS.MD AUTO-GENERATED        ║
╠══════════════════════════════════════════════╣
║  📄 agents.md generated:
║
║  # agents.md
║  > Auto-generated by SilentWriter
║  > Commit: #a4f82c1
║
║  ## Detected Change
║  → login() : new required parameter apiKey
║
║  ## Impact for AI Agents
║  → Agents calling login() must provide apiKey
║  → Fallback: AUTH_KEY_INVALID if omitted
║
║  ## Recommendation
║  → Update prompts of agents using login()
║  → Re-test all agentic workflows
╠══════════════════════════════════════════════╣
║  ⚡ Powered by IBM Granite · WatsonX         ║
╚══════════════════════════════════════════════╝
"""

    # ─── CAS 3 : PR safe → approuvée ───
    else:
        return """
╔══════════════════════════════════════════════╗
║  🤖 SILENTWRITER · IBM GRANITE              ║
╠══════════════════════════════════════════════╣
║  Status: ✅ PR APPROVED                     ║
╠══════════════════════════════════════════════╣
║  🔍 Analysis:
║     • No breaking changes detected
║     • 📊 Impact: All calls compatible
║     • 📚 Documentation: ✓ In sync
║     • 🤖 agents.md: ✓ Up to date
╠══════════════════════════════════════════════╣
║  ⚡ Action:
║     • PR can be merged safely 🔒
║     • Documentation debt: 0 files outdated
╚══════════════════════════════════════════════╝
"""


# ─── INTERFACE GRADIO ───
with gr.Blocks(theme=gr.themes.Soft()) as demo:

    gr.Markdown("# 🤫✍️ SilentWriter Labs")
    gr.Markdown("### AI-powered GitHub guardian — blocks breaking PRs and auto-generates documentation for humans and AI agents")
    gr.Markdown("*Powered by IBM Granite · WatsonX*")

    gr.Markdown("""
---
**Try these 3 examples:**
- `https://github.com/demo/safe-repo` → ✅ PR approved
- `https://github.com/demo/breaking-change` → ⛔ PR blocked  
- `https://github.com/demo/agents-update` → 🤖 agents.md generated
""")

    with gr.Row():
        input_repo = gr.Textbox(
            label="GitHub Pull Request URL",
            placeholder="https://github.com/user/repo/pull/42",
            value="https://github.com/demo/breaking-change"
        )
        btn = gr.Button("🚀 Analyze with IBM Granite", variant="primary")

    output_text = gr.Textbox(label="SilentWriter Analysis", lines=18)

    btn.click(
        fn=silent_writer_logic,
        inputs=input_repo,
        outputs=output_text
    )

    gr.Markdown("""
---
### 🛡️ How it works
1. SilentWriter intercepts every GitHub PR
2. IBM Granite analyzes the code change
3. If breaking change detected → **PR BLOCKED automatically**
4. Auto-generates updated `README.md` + `agents.md`
5. Opens a documentation PR for team review

---
### 🤖 What is agents.md?
Hugging Face recently launched `/agents.md` — a machine-readable API description that AI agents (Claude Code, Codex, Copilot) can read directly.

**SilentWriter is the first tool that guarantees `agents.md` stays synchronized with your actual code after every commit.**

---
*SilentWriter Labs · IBM Hackathon 2025 · Built with IBM Granite*
""")

demo.launch()

