#!/usr/bin/env bash
# ─────────────────────────────────────────────
# 🤫 SilentWriter — Demo Scenario 2
# "The Documentation That Writes Itself"
# ─────────────────────────────────────────────
# Shows how SilentWriter auto-generates
# agents.md when the API changes.
# ─────────────────────────────────────────────

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
BOLD='\033[1m'
NC='\033[0m'

type_text() {
    local text="$1"
    local delay="${2:-0.03}"
    for (( i=0; i<${#text}; i++ )); do
        echo -n "${text:$i:1}"
        sleep "$delay"
    done
    echo
}

# Banner
clear
echo -e "${CYAN}${BOLD}"
echo "╔══════════════════════════════════════════════════╗"
echo "║  🤫 SilentWriter — IBM Bob Hackathon 2025       ║"
echo "║  Scenario 2: The Self-Writing Documentation     ║"
echo "║  \"AI agents that always know the latest API\"     ║"
echo "╚══════════════════════════════════════════════════╝"
echo -e "${NC}"
sleep 2

# ─────────────────────────────────────────────
# ACT 1: THE PROBLEM
# ─────────────────────────────────────────────
echo -e "\n${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}ACT 1: The Documentation Problem${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
sleep 1

echo -e "${BLUE}📋 The team uses AI agents that need up-to-date API docs.${NC}\n"
sleep 1

echo -e "${BLUE}Current agents.md:${NC}\n"
cat << 'EOF'
  # agents.md
  # Last updated: 3 weeks ago
  
  ## OrderService
  - createOrder(userId, items) → Order
  
  ## UserService
  - getUserById(id) → User
EOF

echo -e "\n${YELLOW}⚠️  Problem: This file is manually maintained.${NC}"
echo -e "${YELLOW}⚠️  It's always out of date. AI agents work with stale info.${NC}"
sleep 2

# ─────────────────────────────────────────────
# ACT 2: THE API EVOLVES
# ─────────────────────────────────────────────
echo -e "\n${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}ACT 2: The API Evolves${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
sleep 1

echo -e "${BLUE}👨‍💻 A developer adds new API endpoints:${NC}\n"
sleep 1

cat << 'EOF'
  // New endpoints added to src/api/
  
  // src/api/orders.ts
  export function cancelOrder(orderId: string): void
  export function refundOrder(orderId: string): Refund
  
  // src/api/users.ts
  export function getUserByEmail(email: string): User
  export function deactivateUser(userId: string): void
EOF

echo -e "\n${GREEN}✅ Changes are clean. All SILENT rules pass. PR is merged.${NC}\n"
sleep 1

echo -e "${YELLOW}😟 But nobody updated agents.md...${NC}\n"
sleep 2

# ─────────────────────────────────────────────
# ACT 3: SILENTWRITER DETECTS THE GAP
# ─────────────────────────────────────────────
echo -e "\n${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}ACT 3: SilentWriter Detects the Gap${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
sleep 1

echo -e "${CYAN}🤫 SilentWriter detects API changes via SILENT-006...${NC}\n"
sleep 1

echo -e "${CYAN}📋 Rule triggered: SILENT-006 — agents.md sync${NC}"
sleep 0.5
echo -e "${CYAN}🔍 Scanning new API surface...${NC}"
sleep 1
echo -e "${CYAN}🧠 IBM Granite analyzing new functions...${NC}\n"
sleep 1.5

echo -e "${MAGENTA}${BOLD}┌─────────────────────────────────────────────┐${NC}"
echo -e "${MAGENTA}${BOLD}│  🤖 AUTO-ACTION TRIGGERED                   │${NC}"
echo -e "${MAGENTA}${BOLD}│  SILENT-006: agents.md needs update         │${NC}"
echo -e "${MAGENTA}${BOLD}│  Auto-generating...                         │${NC}"
echo -e "${MAGENTA}${BOLD}└─────────────────────────────────────────────┘${NC}\n"
sleep 2

# ─────────────────────────────────────────────
# ACT 4: THE AUTO-GENERATED DOCS
# ─────────────────────────────────────────────
echo -e "\n${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}ACT 4: The Auto-Generated agents.md${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
sleep 1

echo -e "${GREEN}✅ SilentWriter auto-generates the updated file:${NC}\n"
sleep 1

cat << 'EOF'
  # agents.md
  # Auto-generated by SilentWriter 🤫
  # Last updated: 2026-05-09 14:32 (PR #128)
  
  ## OrderService
  - createOrder(userId, items) → Order
  - cancelOrder(orderId) → void           ← NEW
  - refundOrder(orderId) → Refund         ← NEW
  
  ## UserService
  - getUserById(id) → User
  - getUserByEmail(email) → User          ← NEW
  - deactivateUser(userId) → void         ← NEW
  
  ---
  ## Rules for AI Agents
  When working on this codebase:
  1. Never change function signatures in src/api/
  2. Always add tests for /core changes (≥80% coverage)
  3. Do not add mongoose, sequelize, or typeorm
  4. Never commit secrets or API keys
  
  Maintained automatically by SilentWriter.
  Do not edit manually.
EOF

echo -e "\n${GREEN}✅ agents.md now reflects the exact current API.${NC}"
sleep 2

# ─────────────────────────────────────────────
# ACT 5: THE AI AGENT BENEFIT
# ─────────────────────────────────────────────
echo -e "\n${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}ACT 5: AI Agents Always in Sync${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
sleep 1

echo -e "${CYAN}🧠 When another AI agent works on this repo:${NC}\n"
sleep 1

echo -e "${BLUE}Agent: \"I need to cancel an order. What's the function?\"${NC}"
sleep 0.5
echo -e "${CYAN}Agent reads agents.md...${NC}"
sleep 1
echo -e "${GREEN}Agent: \"Found it! cancelOrder(orderId). It's up to date.\"${NC}\n"
sleep 2

echo -e "${CYAN}${BOLD}┌─────────────────────────────────────────────┐${NC}"
echo -e "${CYAN}${BOLD}│  🧠 AI agents always have the latest API   │${NC}"
echo -e "${CYAN}${BOLD}│  📝 Documentation never goes stale         │${NC}"
echo -e "${CYAN}${BOLD}│  ⚡ Zero developer effort                  │${NC}"
echo -e "${CYAN}${BOLD}└─────────────────────────────────────────────┘${NC}\n"
sleep 2

# ─────────────────────────────────────────────
# ACT 6: THE SILENTWRITER COMMIT
# ─────────────────────────────────────────────
echo -e "\n${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}ACT 6: SilentWriter Commits the Update${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
sleep 1

echo -e "${CYAN}🤫 SilentWriter auto-commits:${NC}\n"
sleep 1

type_text "$ git add agents.md" 0.05
sleep 0.3
type_text "$ git commit -m \"docs: auto-update agents.md [SilentWriter]\"" 0.04
sleep 0.3

echo -e "\n${GREEN}✅ agents.md is always in sync.${NC}"
echo -e "${GREEN}✅ AI agents always know the latest API.${NC}"
echo -e "${GREEN}✅ Developers never write this doc manually again.${NC}\n"
sleep 2

# ─────────────────────────────────────────────
# OUTRO
# ─────────────────────────────────────────────
echo -e "\n${CYAN}${BOLD}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}${BOLD}║  🤫 SilentWriter — Two Scenarios, One Truth     ║${NC}"
echo -e "${CYAN}${BOLD}║                                                  ║${NC}"
echo -e "${CYAN}${BOLD}║  🛡️  Scenario 1: Breaks are blocked automatically ║${NC}"
echo -e "${CYAN}${BOLD}║  🤖 Scenario 2: Docs write themselves            ║${NC}"
echo -e "${CYAN}${BOLD}║                                                  ║${NC}"
echo -e "${CYAN}${BOLD}║  The code review nobody wants to do.             ║${NC}"
echo -e "${CYAN}${BOLD}║  Now handled in silence. 🤫                       ║${NC}"
echo -e "${CYAN}${BOLD}╚══════════════════════════════════════════════════╝${NC}"
echo
echo -e "${CYAN}Powered by IBM Bob · Granite · WatsonX${NC}"
echo -e "${CYAN}github.com/silentwriter-labs/silentwriter${NC}\n"
